# Highlight Pipeline — Configuration
# Generated by new_game.py — update CALIBRATION_ANCHORS as you confirm timestamps.

# -- FIBA LiveStats -----------------------------------------------------------
GAME_ID = "2842822"
FIBA_URL_TEMPLATE = (
    "https://fibalivestats.dcd.shared.geniussports.com/data/{game_id}/data.json"
)
POLL_INTERVAL = 20  # seconds between feed checks (live mode)

# -- League -------------------------------------------------------------------
# Supported: mpbl, uaap, ncaa, jr_mpbl
LEAGUE = "jr_mpbl"

# -- Team identity ------------------------------------------------------------
TEAM      = "jt"        # short folder name
TEAM_TNO  = 2           # tno value in the FIBA feed (1 or 2)
TEAM_NAME = "JT Bulacan Taipan 18u"

# -- Opponent / game identifier -----------------------------------------------
# Output folders: highlights/{LEAGUE}/{TEAM}/{OPPONENT}/{quarter}/
OPPONENT = "sj"

# -- YouTube stream / VOD -----------------------------------------------------
YOUTUBE_STREAM_URL = "https://www.youtube.com/watch?v=p_omHuvlvXE"

# -- VOD replay timing --------------------------------------------------------
TIPOFF_VIDEO_SECONDS = 457

# Calibration anchors — piecewise linear interpolation
# Format: list of (video_seconds, quarter, game_clock_string)
# The tip-off is always the base anchor. Add confirmed plays here.
# More anchors = more accurate timestamps throughout the game.
#
CALIBRATION_ANCHORS = [
    # (video_seconds, quarter, "game_clock MM:SS")
    # Q1
    # Q2
    # Q3
    # Q4
    (537, 1, "09:13"),  # confirmed
    (735, 1, "06:31"),  # confirmed
    (757, 1, "06:08"),  # confirmed
    (911, 1, "04:44"),  # confirmed
    (1198, 1, "01:22"),  # confirmed
    (1376, 1, "00:12"),  # confirmed
    (1646, 2, "08:23"),  # confirmed
    (1721, 2, "07:14"),  # confirmed
    (1753, 2, "06:40"),  # confirmed
    (2232, 2, "01:13"),  # confirmed
    (2338, 2, "00:08"),  # confirmed
    (2862, 3, "08:43"),  # confirmed
    (2954, 3, "07:12"),  # confirmed
    (2980, 3, "06:48"),  # confirmed
    (3007, 3, "06:21"),  # confirmed
    (3035, 3, "05:53"),  # confirmed
    (3183, 3, "04:27"),  # confirmed
    (3236, 3, "04:03"),  # confirmed
    (3292, 3, "03:14"),  # confirmed
    (3497, 3, "00:51"),  # confirmed
    (3519, 3, "00:30"),  # confirmed
    (3542, 3, "00:06"),  # confirmed
    (3868, 4, "07:50"),  # confirmed
    (3932, 4, "07:34"),  # confirmed
    (4106, 4, "06:15"),  # confirmed
    (4272, 4, "05:10"),  # confirmed
    (4297, 4, "04:40"),  # confirmed
    (4471, 4, "03:08"),  # confirmed
    (4560, 4, "02:49"),  # confirmed
    (4591, 4, "02:18"),  # confirmed
    (4614, 4, "01:54"),  # confirmed
    (4859, 4, "00:14"),  # confirmed
]

# Fallback real-time factor (real seconds per game-clock second).
# Used only when extrapolating beyond the last anchor.
REAL_TIME_FACTOR = 2.2

# Seconds of broadcast time between quarters and at halftime.
# Re-confirm from anchor data each game — varies by venue and broadcaster.
QUARTER_BREAK_SECONDS  = 190   # after Q1 and Q3
HALFTIME_BREAK_SECONDS = 700   # halftime break visible in broadcast

# -- Game timing --------------------------------------------------------------
PERIOD_LENGTH    = 10   # minutes per regular quarter
OT_PERIOD_LENGTH = 5    # minutes per overtime period

# -- Video clipping -----------------------------------------------------------
INCLUDE_FREETHROWS = False

CLIP_LEAD_SECONDS = 3    # seconds of footage before detected score
CLIP_TAIL_SECONDS = 3     # seconds of footage after detected score

QUARTER_COMPILE_DELAY = 90    # seconds to wait before compiling (live mode)

# -- Audio verification (Whisper) ---------------------------------------------
AUDIO_VERIFY = True

REVIEW_DIR = "review"

# Crowd noise thresholds (16-bit PCM scale: 0-32767)
CROWD_NOISE_SILENCE_THRESHOLD  = 800
CROWD_NOISE_SPIKE_RATIO        = 1.2
CROWD_NOISE_CONSISTENT_FACTOR  = 4

# -- Paths --------------------------------------------------------------------
RECORDING_DIR  = "recording"
RECORDING_FILE = "recording/stream.ts"
CLIPS_DIR      = "clips"
HIGHLIGHTS_DIR = "highlights"

# -- Facebook (optional) ------------------------------------------------------
FB_ACCESS_TOKEN = ""
FB_PAGE_ID      = ""
FB_POST_MESSAGE_TEMPLATE = (
    "JT Bulacan Taipan 18u Q{quarter} Highlights — {date}\n"
    "#MPBL #PusoPangBayan"
)
