# SiKAT Zamboanga Highlight Pipeline — Configuration
# Generated by new_game.py — update CALIBRATION_ANCHORS as you confirm timestamps.

# -- FIBA LiveStats -----------------------------------------------------------
GAME_ID = "2836518"
FIBA_URL_TEMPLATE = (
    "https://fibalivestats.dcd.shared.geniussports.com/data/{game_id}/data.json"
)
POLL_INTERVAL = 20  # seconds between feed checks (live mode)

# -- League -------------------------------------------------------------------
# Supported: mpbl, uaap, ncaa, jr_mpbl
LEAGUE = "mpbl"

# -- Team identity ------------------------------------------------------------
TEAM     = "zamboanga"       # short folder name
TEAM_TNO = 1                 # tno value in the FIBA feed (1 or 2)
TEAM_NAME = "Zamboanga Sikat"

# -- Opponent / game identifier -----------------------------------------------
# Used to organise output folders: highlights/{LEAGUE}/{TEAM}/{OPPONENT}/{quarter}/
OPPONENT = "ilagan"

# -- YouTube stream / VOD -----------------------------------------------------
YOUTUBE_STREAM_URL = "https://www.youtube.com/watch?v=znHdCMcFUWw"

# -- VOD replay timing --------------------------------------------------------
# Tip-off position in the YouTube video (seconds from the start of the video).
TIPOFF_VIDEO_SECONDS = 543

# Calibration anchors — piecewise linear interpolation
# Format: list of (video_seconds, quarter, game_clock_string)
# The tip-off is always the base anchor. Add confirmed plays here.
# More anchors = more accurate timestamps throughout the game.
#
# How to add one: pause the YouTube video at any scoring play you recognise,
# note the video time and the game-clock on screen, add it here.
#
CALIBRATION_ANCHORS = [
    # (video_seconds, quarter, "game_clock MM:SS")
    # Q1
    # Q2
    # Q3
    # Q4
    (560, 1, "09:44"),  # confirmed
    (579, 1, "08:53"),  # confirmed
    (622, 1, "07:22"),  # confirmed
    (731, 1, "06:28"),  # confirmed
    (831, 1, "04:45"),  # confirmed
    (915, 1, "03:39"),  # confirmed
    (970, 1, "02:56"),  # confirmed
    (1244, 1, "01:11"),  # confirmed
    (1272, 1, "00:47"),  # confirmed
    (1347, 1, "00:25"),  # confirmed
    (1560, 2, "09:52"),  # confirmed
    (1587, 2, "09:22"),  # confirmed
    (1622, 2, "08:48"),  # confirmed
    (2243, 2, "04:04"),  # confirmed
    (2481, 2, "01:45"),  # confirmed
    (3706, 3, "09:34"),  # confirmed
    (3929, 3, "06:18"),  # confirmed
    (3944, 3, "06:00"),  # confirmed
    (4014, 3, "05:09"),  # confirmed
    (4489, 3, "01:20"),  # confirmed
    (4546, 3, "00:51"),  # confirmed
    (4590, 3, "00:29"),  # confirmed
    (5296, 4, "07:03"),  # confirmed
    (5512, 4, "04:56"),  # confirmed
    (5512, 4, "04:27"),  # confirmed
    (5851, 4, "04:10"),  # confirmed
    (5851, 4, "02:16"),  # confirmed
    (5296, 4, "07:03"),  # confirmed
    (5439, 4, "04:27"),  # confirmed
    (5512, 4, "04:10"),  # confirmed
    (5850, 4, "02:16"),  # confirmed
    (5942, 4, "01:53"),  # confirmed
    (6284, 4, "00:54"),  # confirmed
    (6386, 4, "00:49"),  # confirmed
    (6529, 4, "00:37"),  # confirmed
    (6537, 4, "00:33"),  # confirmed
    (6619, 4, "00:24"),  # confirmed
]

# Fallback real-time factor (real seconds per game-clock second).
# Used only when extrapolating beyond the last anchor.
# 2.2 is a safe default; late-game stoppages push this higher.
REAL_TIME_FACTOR = 2.2

# Seconds of broadcast time between quarters and at halftime.
# These are broadcast-dependent — re-confirm from anchor data each game.
QUARTER_BREAK_SECONDS  = 190   # after Q1 and Q3
HALFTIME_BREAK_SECONDS = 700   # halftime break visible in broadcast

# -- Game timing --------------------------------------------------------------
PERIOD_LENGTH    = 10   # minutes per regular quarter
OT_PERIOD_LENGTH = 5    # minutes per overtime period

# -- Video clipping -----------------------------------------------------------
INCLUDE_FREETHROWS = False

CLIP_LEAD_SECONDS = 3.5   # seconds of footage before detected score
CLIP_TAIL_SECONDS = 8     # seconds of footage after detected score

# How long (seconds) after a quarter ends to wait before compiling
# the quarter highlight reel (live mode only).
QUARTER_COMPILE_DELAY = 90

# -- Audio verification (Whisper) ---------------------------------------------
AUDIO_VERIFY = True

# Whisper model size. Tradeoff: speed vs accuracy.
#   tiny  ~75 MB  ~1s/clip  (CPU)
#   base  ~145MB  ~2s/clip  (CPU)   recommended default
#   small ~460MB  ~5s/clip  (CPU)
WHISPER_MODEL = "base"

REVIEW_DIR = "review"

AUDIO_CONFIRM_KEYWORDS = [
    # Team / city
    "sikat", "zamboanga",
    # Player surnames (update with FIBA familyName values for this game)
    "are", "felicilda", "turco", "lazaro", "luciano",
    "calisay", "bunag", "gabat", "rojas", "fornilos", "salim",
    # English basketball calls
    "scores", "basket", "made", "two", "three", "triple",
    "free throw", "and one",
    # Filipino / Tagalog calls common in MPBL broadcasts
    "puntos", "dos puntos", "tres puntos",
    "nag-score", "nagsc", "nagscore",
    "isang", "dalawa", "tatlo",
]

AUDIO_REJECT_KEYWORDS = ['ilagan', 'cowboys']

# -- Paths --------------------------------------------------------------------
RECORDING_DIR  = "recording"
RECORDING_FILE = "recording/stream.ts"   # raw yt-dlp / ffmpeg capture (live mode)
CLIPS_DIR      = "clips"                 # individual scoring clips
HIGHLIGHTS_DIR = "highlights"            # compiled quarter reels

# -- Facebook (optional) ------------------------------------------------------
FB_ACCESS_TOKEN = ""
FB_PAGE_ID      = ""
FB_POST_MESSAGE_TEMPLATE = (
    "SiKAT Zamboanga Q{quarter} Highlights — {date}\n"
    "#SiKATZamboanga #MPBL #PusoPangBayan"
)
