# Highlight Pipeline — Configuration
# Generated by new_game.py — update CALIBRATION_ANCHORS as you confirm timestamps.

# -- FIBA LiveStats -----------------------------------------------------------
GAME_ID = "2836529"
FIBA_URL_TEMPLATE = (
    "https://fibalivestats.dcd.shared.geniussports.com/data/{game_id}/data.json"
)
POLL_INTERVAL = 20  # seconds between feed checks (live mode)

# -- League -------------------------------------------------------------------
# Supported: mpbl, uaap, ncaa, jr_mpbl
LEAGUE = "mpbl"

# -- Team identity ------------------------------------------------------------
TEAM      = "zam_sj"        # short folder name
TEAM_TNO  = 1           # tno value in the FIBA feed (1 or 2)
TEAM_NAME = "Zamboanga Sikat"

# -- Opponent / game identifier -----------------------------------------------
# Output folders: highlights/{LEAGUE}/{TEAM}/{OPPONENT}/{quarter}/
OPPONENT = "sj"

# -- YouTube stream / VOD -----------------------------------------------------
YOUTUBE_STREAM_URL = "https://www.youtube.com/watch?v=4idaXCLfL8A"

# -- VOD replay timing --------------------------------------------------------
TIPOFF_VIDEO_SECONDS = 1446

# Calibration anchors — piecewise linear interpolation
# Format: list of (video_seconds, quarter, game_clock_string)
# The tip-off is always the base anchor. Add confirmed plays here.
# More anchors = more accurate timestamps throughout the game.
#
CALIBRATION_ANCHORS = [
    # (video_seconds, quarter, "game_clock MM:SS")
    # Q1
    # Q2
    # Q3
    # Q4
    (1493, 1, "09:15"),  # confirmed
    (1703, 1, "07:42"),  # confirmed
    (1746, 1, "06:58"),  # confirmed
    (2109, 1, "04:16"),  # confirmed
    (2259, 1, "03:18"),  # confirmed
    (2299, 1, "02:36"),  # confirmed
    (3205, 2, "06:40"),  # confirmed
    (3613, 2, "04:26"),  # confirmed
    (4146, 2, "00:03"),  # confirmed
]

# Fallback real-time factor (real seconds per game-clock second).
# Used only when extrapolating beyond the last anchor.
REAL_TIME_FACTOR = 2.2

# Seconds of broadcast time between quarters and at halftime.
# Re-confirm from anchor data each game — varies by venue and broadcaster.
QUARTER_BREAK_SECONDS  = 190   # after Q1 and Q3
HALFTIME_BREAK_SECONDS = 700   # halftime break visible in broadcast

# -- Game timing --------------------------------------------------------------
PERIOD_LENGTH    = 10   # minutes per regular quarter
OT_PERIOD_LENGTH = 5    # minutes per overtime period

# -- Video clipping -----------------------------------------------------------
INCLUDE_FREETHROWS = False

CLIP_LEAD_SECONDS = 3    # seconds of footage before detected score
CLIP_TAIL_SECONDS = 4     # seconds of footage after detected score

QUARTER_COMPILE_DELAY = 90    # seconds to wait before compiling (live mode)

# -- Audio verification (crowd noise detection) -------------------------------
# Verifies interpolated clips by detecting crowd noise energy spikes.
# Anchored (manually calibrated) clips skip verification entirely.
AUDIO_VERIFY = True

REVIEW_DIR = "review"

# Crowd noise thresholds (16-bit PCM scale: 0–32767)
# Below this RMS value the clip is considered silent (dead ball / wrong moment)
CROWD_NOISE_SILENCE_THRESHOLD  = 800
# Tail window must be at least this ratio louder than lead to confirm basket
CROWD_NOISE_SPIKE_RATIO        = 1.2
# If overall RMS is this many times the silence threshold, treat as confirmed
# regardless of spike (handles fast breaks where crowd is already loud)
CROWD_NOISE_CONSISTENT_FACTOR  = 4

# -- Paths --------------------------------------------------------------------
RECORDING_DIR  = "recording"
RECORDING_FILE = "recording/stream.ts"
CLIPS_DIR      = "clips"
HIGHLIGHTS_DIR = "highlights"

# -- Facebook (optional) ------------------------------------------------------
FB_ACCESS_TOKEN = ""
FB_PAGE_ID      = ""
FB_POST_MESSAGE_TEMPLATE = (
    "Zamboanga Sikat Q{quarter} Highlights — {date}\n"
    "#MPBL #PusoPangBayan"
)
